### ISSUE TITLE
Moving to new installation

### ISSUE THREAD

**Issue by tka85** [eugene-khyst/letsencrypt-docker-compose#58]
I am using letsencrypt-docker-compose as a rev proxy to several docker containers. But now I want to move some of the containers to a new instance. How would I go about the installation of letsencrypt-docker-compose on the new instance?

Do I simply do setup `cli.sh config` from the start? When it asks about generating staging certs, there is no longer the need (already did this in the current instance), but I suppose it will fail to generate new production certs as they already exist.

Or is it better to simply copy over the relevant parts of the `config.json` and the relevant subfolders of `nginx-conf/`?

**Comment by eugene-khyst** [comment]
Hi, @tka85
You can repeat letsencrypt-docker-compose configuration on a new server instance from scratch with `cli.sh config`.
You can even repeat obtaining staging certificates to verify that infrastructure on a new server is properly configured.
Let's Encrypt has a rate limit of obtaining production certificates, you can not obtain production certificates often.
But if you will receive staging and then production certificates _only once_ for the new server instance it will not be a problem at all.
Certificates are stored in the Docker volume. You have to export certificates and Nginx config from volumes first, then import these files into the corresponding volumes on a new server instance. If you are interested in this approach, I will describe the required steps.

**Comment by tka85** [comment]
I'm fine with repeating from scratch cli.sh config on new instance.

One more thing. What about the existing instance? I assume I should run cli.sh to remove the domains of the containers that are moving to the new instance. Anything else?

**Comment by eugene-khyst** [comment]
The high-level algorithms is:

1. Update A, AAAA, CNAME DNS records to point to new server instance's IP address. Wait until the changes are applied (DNS changes may take long).
2. Remove domains from the old server instance using CLI.
3. Config these domains on a new server instance using CLI (obtaining Staging certificates step is still recommended).

Also worth mentioning that such algorithm assumes downtime.

**Comment by tka85** [comment]
Thanks @eugene-khyst 

That pretty much worked OK. 

For some reason some of the staging certificates did not work well. Gave an error on Ffox which was not the common case of "Accept the risk" to proceed. It was a deadend about MITM attach. It was not a delayed DNS record propagation. 

But I removed and repeated the process all the way to production certs and all went well in the end.
