### ISSUE TITLE
Waiting for Let's Encrypt certificate for <bad-domain-name>

### ISSUE THREAD

**Issue by tka85** [eugene-khyst/letsencrypt-docker-compose#64]
I added a new service but I mistyped the domain name. Something like `example.orgg` instead of `.org`.

I realized it too late and re-run to remove it. Removed successfully (no traces in `config.json` or under `nginx-conf/`) but now I see in the logs of `letsencrypt-docker-compose-nginx-1` constantly the message `Waiting for Let's Encrypt certificate for example.orgg`.

Something I can do to clean up so this stops?

**Comment by eugene-khyst** [comment]
Hi @tka85,

Try running:

```bash
docker compose restart --no-deps nginx
```

This is a bug. After removing the domain, CLI reloads Nginx config: https://github.com/eugene-khyst/letsencrypt-docker-compose/blob/f4169533dc30f30cf0401daa1b6919bdf6cb2217/cli/src/cli.js#L264C13-L264C13

But reloading Nginx config doesn't have any effect on this line of the Bash script: https://github.com/eugene-khyst/letsencrypt-docker-compose/blob/f4169533dc30f30cf0401daa1b6919bdf6cb2217/nginx/start-nginx.sh#L21
After removing the domain CLI should restart `nginx` container. 

I will fix it. Thanks for reporting the bug.

**Comment by eugene-khyst** [comment]
@tka85 , have you solved the problem?

**Comment by tka85** [comment]
Yep. Thank you very much. 

Worked like a charm!
